#!/usr/bin/env python

import yaml

extensions = yaml.load(open('.github/workflows/test_extensions.yml'), Loader=yaml.FullLoader)['jobs']['test']['strategy']['matrix']['extension']

with open("README.md", "w") as f:
    f.write("""\
# DataLad Extensions

DataLad extensions and their releases/status:
""")

    # TODO: link to per-extension cron-github-CI results
    for e in extensions:
        edash = e.replace("_", "-")
        f.write(f"- [{e}](https://github.com/datalad/{edash}):"
            f' [![Travis tests status](https://secure.travis-ci.org/datalad/{edash}.png?branch=master)](https://travis-ci.org/datalad/{edash})'
            f' [![codecov.io](https://codecov.io/github/datalad/{edash}/coverage.svg?branch=master)](https://codecov.io/github/datalad/{edash}?branch=master)'
            f' [![GitHub release](https://img.shields.io/github/release/datalad/{edash}.svg)](https://GitHub.com/datalad/{edash}/releases/)'
            f' [![PyPI version fury.io](https://badge.fury.io/py/{edash}.svg)](https://pypi.python.org/pypi/{edash}/)'
            f' [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/datalad/{edash}.svg)](http://isitmaintained.com/project/datalad/{edash} "Average time to resolve an issue")'
            f' [![Percentage of issues still open](http://isitmaintained.com/badge/open/datalad/{edash}.svg)](http://isitmaintained.com/project/datalad/{edash} "Percentage of issues still open")'
            f' ![Conda](https://anaconda.org/conda-forge/{edash}/badges/version.svg)'
            #[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3368666.svg)](https://doi.org/10.5281/zenodo.3368666)
            #f"[![Documentation](https://readthedocs.org/projects/{edash}/badge/?version=latest)](http://{edash}.rtfd.org)"
            #f"[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) 
            '\n'
        )
