#!/bin/bash -x

# Enable build flags that need extra C libs, so are not enabled by
# default. Needs this run to install them:
#       brew install --bottle libmagic pkg-config
export BUILDEROPTIONS="--extra-include-dirs=$HOME/homebrew/include --extra-lib-dirs=$HOME/homebrew/lib"
export OSX_MAGIC_FILE="$(brew list --verbose libmagic| grep magic.mgc | head -n 1)"
cat standalone/osx/stack.yaml > stack.yaml.autobuild
export BUILDERCOMMONOPTIONS="--stack-yaml stack.yaml.autobuild"

export BUILDER=stack
stack setup --stack-yaml stack.yaml.autobuild
# use stack version of ghc
GHC="stack --stack-yaml stack.yaml.autobuild ghc --"
export GHC

make osxapp || exit 4
