#!/bin/bash
#
set -eu

mountpoint="$1"
size="$2"

image="$mountpoint.img"

sudo apt-get update -qq
sudo apt-get install dosfstools

# VFAT FS in a box
sudo dd if=/dev/zero "of=$image" "count=$size" bs=1M
sudo mkfs.vfat "$image"

# mount
sudo mkdir "$mountpoint"
sudo mount -o "uid=$(id -u),gid=$(id -g)" "$image" "$mountpoint"
